### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by tombruijn** [mongoid/mongo_session_store#16]
See @drgcms's [fork](https://github.com/brianhempel/mongo_session_store/compare/master...drgcms:rails5)'s fork for a start.

Related: https://github.com/brianhempel/mongo_session_store/issues/33

**Comment by macool** [comment]
:yey:

**Comment by tombruijn** [comment]
I've created a PR that adds support for this in #31.
You can try it out @macool and let me know if it works :)

**Comment by gencer** [comment]
@tombruijn, I tested against Rails5.0.1 and 5.1.0. All sessions are successfully created and used. Thanks!.

**Comment by tombruijn** [comment]
Great to hear! Thanks for the feedback :)

**Comment by tombruijn** [comment]
Rails 5.0 support released under gem version 3.1. The devise dependency is too strict right now on railties for me to test it against Rails 5.1.

**Comment by gencer** [comment]
I successfully tested on 5.1 using devise's **master** branch. No issues so far. I will closely monitor all features and will report in any issue arises.

**Comment by tombruijn** [comment]
@gencer thanks again for the feedback :)
I've added a Rails 5.1 test run on Travis against devise master in #32

**Comment by TheR2** [comment]
Tested on Rails 5.0.2 and Ruby 2.4.1. Works as expected. Sessions created with older version are preserved.

Good work. Thank you.

by TheR
