### ISSUE TITLE
Update repo description

### ISSUE THREAD

**Issue by tombruijn** [mongoid/mongo_session_store#33]
## Description

On https://github.com/mongoid/mongo_session_store/ the repo description is outdated:

> Rails session store class implemented for MongoMapper and Mongoid

This should be something along the lines of:

> MongoSessionStore is a Rails-compatible session store for MongoDB using either Mongoid or the MongoDB Ruby Driver. It also allows for custom Mongo session store that works with any (or no!) Mongo ODM.

The tags should be: mongoid, mongodb, rails, session-management, session-store

## Url

The repo description also links to http://boldr.net/rails-sessions-mongodb. The link is dead, so is its parent website.

Can someone update this to have no link, link the repo itself (which seem redundant) or link to the mongoid community page?

@dblock could you help?

**Comment by dblock** [comment]
@did and @nmerouze are both admins on this repo, I am just cheerleading, so will let you guys sort that out :)

**Comment by nmerouze** [comment]
I put you both @dblock and @tombruijn admins.

**Comment by tombruijn** [comment]
Great! Thanks :)
Updated the description, url and topics the repo. Should be good now
