### ISSUE TITLE
Issue when upgrading to latest rails 6.0.2.1/mongoid 7.0.5/rack 2.1.1 versions.

### ISSUE THREAD

**Issue by streetlogics** [mongoid/mongo_session_store#42]
I'm not exactly sure which combo yields the error, but the basic gist is that I was trying to upgrade our rails app to Rails 6, latest mongoid, and the latest rack versions.  Somewhere along the way, doing that started throwing an "undefined method `bson_type' for #<Rack::Session::SessionId:0x00007f9c9e2c4d08>" error.  

I ended up reporting the issue to the guys at mongoid since I wasn't sure if it was mongoid or the bson gems - https://jira.mongodb.org/browse/RUBY-2095 .  They ended up asking if I could recreate the issue in a rails app, so I did, and upon doing so realized that the issue was actually surfacing from the mongo_session_store gem itself (https://github.com/mongoid/mongo_session_store/blob/master/lib/mongo_session_store/mongo_store_base.rb#L49)

For anyone else that comes across this, until it's patched in this repo you can monkey patch things with a file in `config/initializers/mongo_session_store_monkey_patch` with the following code:
```
module ActionDispatch
  module Session
    class MongoStoreBase < AbstractStore
      def find_or_initialize_session(id)
        existing_session = (id && session_class.where(:_id => id.to_s).first)
        session = existing_session if existing_session
        session ||= session_class.new(:_id => generate_sid)
        [session._id, session]
      end
    end
  end
end
```

**Comment by tombruijn** [comment]
Fixed in #46
