### ISSUE TITLE
Undefined method: session_store=

### ISSUE THREAD

**Issue by khueue** [mongoid/mongo_session_store#8]
Hi! Got this error when I followed the install instructions for Mongoid running Rails 3.0.3:

sample_app/config/initializers/session_store.rb:10:in `<top (required)>': undefined method`session_store=' for ActionController::Base:Class (NoMethodError)

I changed the line :

ActionController::Base.session_store = :mongoid_store

to:

NameOfMyApp::Application.config.session_store = :mongoid_store

Seems to be working now!

**Comment by tombruijn** [comment]
Fixed in #13. Updated in README for version 3.
